name: PlayerKitsPlus
version: '2.0.0'
main: me.zombieman.playerkitsplus.PlayerKitsPlus
api-version: '1.13'
commands:
  createkit:
    permission: playerkitsplus.command.createkit
  deletekit:
    permission: playerkitsplus.command.deletekit
  kit:
    permission: playerkitsplus.command.kit
  showkit:
    permission: playerkitsplus.command.showkit
  resetcooldown:
    permission: playerkitsplus.command.resetcooldown
  changetimer:
    permission: playerkitsplus.command.changetimer

permissions:
  playerkitsplus.command.createkit:
    default: op
  playerkitsplus.command.deletekit:
    default: op
  playerkitsplus.command.kit:
    default: op
  playerkitsplus.command.showkit:
    default: op
  playerkitsplus.command.resetcooldown:
    default: op
  playerkitsplus.command.changetimer:
    default: op